name: ruqe
description: Ruqe brings the programming concepts found in Rust into Dart, such as the Result and Option, etc.
version: 1.0.0
homepage: https://github.com/thecre8tor/ruqe
repository: https://github.com/thecre8tor/ruqe.git
issue_tracker: https://github.com/thecre8tor/ruqe/issues

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
